/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Rnc } from "./Rnc";
import { RncCountArgs } from "./RncCountArgs";
import { RncFindManyArgs } from "./RncFindManyArgs";
import { RncFindUniqueArgs } from "./RncFindUniqueArgs";
import { DeleteRncArgs } from "./DeleteRncArgs";
import { RncService } from "../rnc.service";
@graphql.Resolver(() => Rnc)
export class RncResolverBase {
  constructor(protected readonly service: RncService) {}

  async _rncsMeta(
    @graphql.Args() args: RncCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Rnc])
  async rncs(@graphql.Args() args: RncFindManyArgs): Promise<Rnc[]> {
    return this.service.rncs(args);
  }

  @graphql.Query(() => Rnc, { nullable: true })
  async rnc(@graphql.Args() args: RncFindUniqueArgs): Promise<Rnc | null> {
    const result = await this.service.rnc(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Rnc)
  async deleteRnc(@graphql.Args() args: DeleteRncArgs): Promise<Rnc | null> {
    try {
      return await this.service.deleteRnc(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
